# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PDFGenerator', '~> 3.0'
pod 'TesseractOCRiOS'
pod 'SwiftGoogleTranslate'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

end
